version: '3'
services:
    base_webpack:
        image: base_webpack
        build: .
        restart: always
        ports:
            - '3000:3000'
        volumes:
            - .:/app
        command: npm start
